$(function(){
	var data=[
		{
			name:'张三',
			age:'18',
			school:'河南郑州大学',
			professional:'计算机',
			course:[
				{
					textbook:'计算机基础',
					hour:'66',
					teacher:'张老师',
				},
				{
					textbook:'HTML+CSS基础',
					hour:'78',
					teacher:'王老师',
				},
				{
					textbook:'JavaScript',
					hour:'56',
					teacher:'李老师',
				},
				{
					textbook:'JQuery',
					hour:'88',
					teacher:'赵老师',
				}
			]
		},
		{
			name:'李四',
			age:'19',
			school:'河南大学',
			professional:'机械制造',
			course:[
				{
					textbook:'计算机基础',
					hour:'66',
					teacher:'王老师',
				},
				{
					textbook:'工艺加工',
					hour:'78',
					teacher:'王老师',
				},
				{
					textbook:'机械制图',
					hour:'56',
					teacher:'李老师',
				},
				{
					textbook:'C语言',
					hour:'88',
					teacher:'赵老师',
				}
			]
		},{
			name:'王五',
			age:'18',
			school:'河南农业职业学院',
			professional:'java大数据',
			course:[
				{
					textbook:'计算机基础',
					hour:'66',
					teacher:'张老师',
				},
				{
					textbook:'JAVA基础',
					hour:'78',
					teacher:'王老师',
				},
				{
					textbook:'JAVA高级',
					hour:'56',
					teacher:'李老师',
				},
				{
					textbook:'JSP',
					hour:'88',
					teacher:'赵老师',
				}
			]
		}
	]
	function init(){
		var str='';
		for(var i=0;i<data.length;i++){
			str+='<div class="list">';
			str+='<h1>姓名：'+data[i].name+'</h1>';
			str+='<h2>年龄：'+data[i].age+'</h2>';
			str+='<h3>所在学校：'+data[i].school+'</h3>';
			str+='<h4>所学专业：'+data[i].professional+'</h4>';
			for(var j=0;j<data[i].course.length;j++){
				str+='<ul>';
					str+='<li>'+data[i].course[j].textbook+'</li>'
				str+='</ul>';
			}
			str+='</list>';			
		}
		$('.box').html(str);
	}
	init();
})
